### ISSUE TITLE
Docker annotations with main function

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerinax/docker#124]
**Description:**
Requesting a feature to support docker annotations with main function

**Comment by hemikak** [comment]
Is this still needed ? Given that tasks can now be executed as a service[1]. 

[1] - https://ballerina.io/learn/by-example/task-service-appointment.html

**Comment by raj-rajaratnam** [comment]
I think it's still needed because we have a task scheduler timer feature that can be used with main [1]

[1] https://ballerina.io/learn/by-example/task-scheduler-timer.html
