### ISSUE TITLE
Add copy directory support to Docker extenstion

### ISSUE THREAD

**Issue by anuruddhal** [ballerinax/docker#125]
**Description:**
At the moment only files can be specified with @docker:CopyFiles{} annotation. We should add support to copy a directory and it's subdirectories & files to docker image.

**Suggested Labels:**
Enhancement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinax/docker/pull/197
