### ISSUE TITLE
Junit Test Failure while installing ballerina docker

### ISSUE THREAD

**Issue by Anshulrathi** [ballerinax/docker#135]
**Description:**
Junit is failing 

**Suggested Labels:**
Ballerina Docker

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
mvn clean install
[junit Log.txt](https://github.com/ballerinax/docker/files/2458726/junit.Log.txt)

**Related Issues:**

**Comment by vinok88** [comment]
Hi, I have run the test and it passes. Also manually validated the behavior as well that is tested by this unit test. Can you please make sure you are running the latest code by taking pull from ballerinax repo.

**Comment by Shan1024** [comment]
In my experience, this happens when the docker is not installed or not running in the machine.

**Comment by vinok88** [comment]
Well, this is a unit test that just tests a utility method that does some string manipulation. It does not require docker.

**Comment by Shan1024** [comment]
I just saw the attached log. You are correct. This is not related to docker being not available.

**Comment by hemikak** [comment]
@Anshulrathi Do you have any other information on this issue ? What OS you are using ? Are you still getting this issue ?

**Comment by Anshulrathi** [comment]
I switched to the old version of ballerina to rid of this issue. Still
using the old version.

Thanks & Regards
Anshul Rathi

**Comment by hemikak** [comment]
@Anshulrathi We would like to know more information to reproduce this issue ?

OS:
Java version:
Java vendor:
Ballerina version which caused the issue:
Ballerina version you stated as the old version:

**Comment by hemikak** [comment]
Closing due to no responses. Please reopen if issue still persists. Also note that JUnit tests are not there anymore as the tests are moved to testng.
