### ISSUE TITLE
Wrong argument order to ballerina command

### ISSUE THREAD

**Issue by rdhananjaya** [ballerinax/docker#141]
**Description:**
In generated Docker file, order of arguments to ballerina command is wrong.

Currently generated Docker CMD 
`CMD ballerina run hello_service.balx --config /home/ballerina/conf/twitter.toml`

This should be (in 0.982.0)
`CMD ballerina run --config /home/ballerina/conf/twitter.toml hello_service.balx`

**Affected Product Version:**
0.982

**Steps to reproduce:**
Follow docker section of Ballerina [quick-tour](https://ballerina.io/learn/quick-tour/).

**Comment by NatashaWso2** [comment]
This issue is fixed with https://github.com/ballerinax/docker/pull/139, hence closing this issue.
