### ISSUE TITLE
dockerHost annotation is not working

### ISSUE THREAD

**Issue by lakwarus** [ballerinax/docker#15]
Tested with minikube

lakmals-mbp:sample1 lakmal$ minikube docker-env
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/lakmal/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:

@docker:configuration{dockerHost:"tcp://192.168.99.100:2376"}

error : 
error [docker plugin]: error building docker image: Connection reset
ballerina: error writing program file 'hello_world_docker.balx'

**Comment by anuruddhal** [comment]
Need to provide cert path in the annotation.
```
@docker:configuration {
 dockerHost:"tcp://192.168.99.100:2376", 
 dockerCertPath:"/Users/lakmal/.minikube/certs"
}
```
