### ISSUE TITLE
Fix docker error during ballerina build.

### ISSUE THREAD

**Issue by gcaraman** [ballerinax/docker#311]
**Description:**
`ballerina build [module-name]` returns an error:
```
error [docker plugin]: module [ballerinaplayground/playground:0.1.0] unable to connect to server:   org.apache.http.client.ClientProtocolException
```

**Affected Product Version:**
Ballerina 1.0.4
**OS, DB, other environment details and versions:**    
Windows 10, Docker Desktop 2.1.0.5

**Steps to reproduce:**
* Create a project with modules and add docker to it:
```
@docker:Expose {}
listener http:Listener listenerName = new(9090);

@docker:Config { name: "dockerName", tag: "v1.0", dockerHost: "localhost"}  // Expose Docker daemon to localhost for this to work
service serviceName on listenerName {
```
* Run `ballerina build [module-name]`

**Note: If docker is used for a single file (Ballerina build file.bal) everything works fine**

**Comment by hemikak** [comment]
Hi @gcaraman ,

Can you tryout this solution: https://github.com/wso2/ballerina-integrator/issues/723

Regards,
Hemika

**Comment by gcaraman** [comment]
Hi, this option is already enabled, without it even the single file won't work.

**Comment by hemikak** [comment]
Hi @gcaraman ,

Can you change the name of the docker image name's repository to lowercase ?  

```ballerina
@docker:Config { name: "docker-name", tag: "v1.0", dockerHost: "localhost"}
```

**Comment by gcaraman** [comment]
@hemikak, that worked, tho the error didn't even remotely suggest that issue )

**Comment by hemikak** [comment]
@gcaraman , Yes it required to have a valid image name. The error message needs to be revisited. I'll keep this open til its fixed.

**Comment by ankitashine132** [comment]
Hi @hemikak I am facing same issue in wso2 microgateway 3.1.0 and docker is installed in linux centos.
Below is my deployment-config.toml file
[docker]
  [docker.dockerConfig]
    enable = true
    #name = "petstoretest"
    #registry = 'docker.wso2.com'
    #tag = 'v1'
    #buildImage = 'true'
    #dockerHost = '10.*.*.*'
    #dockerCertPath = ''
    #baseImage = 'wso2/wso2micro-gw:3.0.1'
    #enableDebug = 'true'
    #debugPort = '5050'
    #push = ''
  [docker.dockerCopyFiles]
    enable = true
    [[docker.dockerCopyFiles.files]]
        source = '/***/micro-gw.conf'
        target = '/home/ballerina/conf/micro-gw.conf'
        isBallerinaConf = true
