### ISSUE TITLE
Getting trivy version in travis is not stable

### ISSUE THREAD

**Issue by inzamam-iqbal** [ballerinax/docker#379]
In travis we use the following line to get the latest version. It sometimes works and most of the time it doesn't. Travis build in my PR was failing several times due to this. But after restarting it for like four times, it worked. 
https://github.com/ballerinax/docker/blob/a17f09090f79f1806575a58245d67a5acfd4e06b/.travis.yml#L39

This is the error message is 
![bug](https://user-images.githubusercontent.com/15038177/77515474-97452280-6e9e-11ea-8727-599ca5b831b8.png)

**Comment by inzamam-iqbal** [comment]
I put a fix for this as part of PR #358 but that PR 's Travis build is failing due to #380

**Comment by hemikak** [comment]
Please recheck now.
